server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /data/loki/positions.yaml

clients:
  - url: http://172.31.9.248:3100/loki/api/v1/push


scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: var-logs
      __path__: /var/log/*log
      server_name: atdd-staging-server

- job_name: app-log
  static_configs:
  - targets:
      - localhost
    labels:
      job: applogs
      __path__: /srv/applogs/*log
      server_name: atdd-staging-server

- job_name: gunicorn-log
  static_configs:
  - targets:
      - localhost
    labels:
      job: gunicorn
      __path__: /var/log/gunicorn/*log
      server_name: atdd-staging-server