server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /data/loki/positions.yaml

clients:
  - url: http://172.31.5.229:3100/loki/api/v1/push


scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: var-logs
      __path__: /var/log/*log
      server_name: 

- job_name: app-log
  static_configs:
  - targets:
      - localhost
    labels:
      job: applogs
      __path__: /srv/applogs/*log
      server_name: 

- job_name: gunicorn-log
  static_configs:
  - targets:
      - localhost
    labels:
      job: gunicorn
      __path__: /var/log/gunicorn/*log
      server_name: 

- job_name: journal-log
  static_configs:
  - targets:
      - localhost
    labels:
      job: journal
      __path__: /var/log/journal/*log
      server_name: 
      
- job_name: nginx-log
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginx
      __path__: /var/log/nginx/*log
      server_name: 

- job_name: redis-log
  static_configs:
  - targets:
      - localhost
    labels:
      job: redis
      __path__: /var/log/redis/*log
      server_name: 

- job_name: supervisor-log
  static_configs:
  - targets:
      - localhost
    labels:
      job: supervisor
      __path__: /var/log/supervisor/*log
      server_name: 